#!/usr/bin/env python3
"""
Synchronize version numbers across all Amphi packages.

This script updates version numbers in package.json and _version.py files
for all three Amphi packages to ensure synchronized releases.

Usage:
    python update_versions.py <version>

Example:
    python update_versions.py 0.9.6
"""

import sys
import json
from pathlib import Path


def update_version(version: str):
    """Update version in all package files."""

    # Get the amphi-etl root directory (two levels up from this script)
    base_dir = Path(__file__).parent.parent

    print(f"Updating all packages to version {version}")
    print(f"Base directory: {base_dir}")
    print()

    # Update jupyterlab-amphi
    print("📦 Updating jupyterlab-amphi...")
    jupyterlab_dir = base_dir / "jupyterlab-amphi"
    update_package_json(jupyterlab_dir / "package.json", version)
    update_version_py(jupyterlab_dir / "_version.py", version)

    # Update amphi-scheduler
    print("\n📦 Updating amphi-scheduler...")
    scheduler_dir = base_dir / "amphi-scheduler"
    update_package_json(scheduler_dir / "package.json", version)
    update_version_py(scheduler_dir / "_version.py", version)
    update_version_py(
        scheduler_dir / "packages/pipeline-scheduler/pipeline_scheduler/version.py",
        version
    )

    # Update amphi-etl
    print("\n📦 Updating amphi-etl...")
    etl_dir = base_dir / "amphi-etl"
    update_package_json(etl_dir / "package.json", version)
    update_version_py(etl_dir / "amphi/_version.py", version, auto_generated=True)
    update_setup_py(etl_dir / "setup.py", version)

    print(f"\n✅ Successfully updated all packages to version {version}")


def update_package_json(file_path: Path, version: str):
    """Update version in package.json."""
    try:
        with open(file_path, 'r') as f:
            data = json.load(f)

        old_version = data.get('version', 'unknown')
        data['version'] = version

        with open(file_path, 'w') as f:
            json.dump(data, f, indent=4)
            f.write('\n')

        print(f"  ✓ {file_path.relative_to(file_path.parent.parent.parent)}: {old_version} → {version}")
    except Exception as e:
        print(f"  ✗ Failed to update {file_path}: {e}")
        sys.exit(1)


def update_version_py(file_path: Path, version: str, auto_generated: bool = False):
    """Update version in Python _version.py file."""
    try:
        if auto_generated:
            # amphi-etl uses auto-generated format
            content = f"""# This file is auto-generated by Hatchling. As such, do not:
#   - modify
#   - track in version control e.g. be sure to add to .gitignore
__version__ = '{version}'
"""
        else:
            # jupyterlab-amphi and amphi-scheduler use simple format
            content = f'''__version__ = "{version}"
'''

        with open(file_path, 'w') as f:
            f.write(content)

        print(f"  ✓ {file_path.relative_to(file_path.parent.parent.parent)}")
    except Exception as e:
        print(f"  ✗ Failed to update {file_path}: {e}")
        sys.exit(1)


def update_setup_py(file_path: Path, version: str):
    """Update version in setup.py file (for amphi-etl)."""
    try:
        import re

        with open(file_path, 'r') as f:
            content = f.read()

        # Update main version
        content = re.sub(r"version='[^']*'", f"version='{version}'", content)

        # Update dependency versions
        content = re.sub(r"jupyterlab-amphi==[0-9.]+", f"jupyterlab-amphi=={version}", content)
        content = re.sub(r"amphi-scheduler==[0-9.]+", f"amphi-scheduler=={version}", content)

        with open(file_path, 'w') as f:
            f.write(content)

        print(f"  ✓ {file_path.relative_to(file_path.parent.parent.parent)}")
    except Exception as e:
        print(f"  ✗ Failed to update {file_path}: {e}")
        sys.exit(1)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python update_versions.py <version>")
        print("Example: python update_versions.py 0.9.6")
        sys.exit(1)

    version = sys.argv[1].strip()

    # Validate version format (basic check)
    parts = version.split('.')
    if len(parts) < 2 or not all(part.isdigit() for part in parts):
        print(f"Error: Invalid version format '{version}'")
        print("Expected format: X.Y.Z (e.g., 0.9.6 or 1.0.0)")
        sys.exit(1)

    update_version(version)
